services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flashcards
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    container_name: migration
    build:
      context: ./packages/api
      dockerfile: Dockerfile-dev
    command: python src/manage.py migrate
    environment:
      - DB_NAME=flashcards
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  api:
    container_name: api
    build:
      context: ./packages/api
      dockerfile: Dockerfile-dev
    ports:
      - "8000:8000"
    volumes:
      - ./packages/api:/app
    networks:
      - app-network
    environment:
      - DB_HOST=db

    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

  ## Development Web build
  # web:
  #   container_name: web
  #   build:
  #     context: ./packages/web
  #     dockerfile: Dockerfile-dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./packages/web:/app
  #     - /app/node_modules
  #   environment:
  #     - PORT=3000
  #   networks:
  #     - app-network
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     migration:
  #       condition: service_completed_successfully

  ## Production Web build
  web:
    container_name: web
    build:
      context: ./packages/web
      dockerfile: Dockerfile-prod
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
