version: "3.8"

services:
  api:
    build: ./packages/api
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - app-network

  web:
    build: ./packages/web
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - app-network
    depends_on:
      - api

  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flashcards
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
